### ISSUE TITLE
Streets being matched as points & having a higher lower bound than upper bound in the section attribute

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_shared_streets_conflator#12]
some reference came back having a section value like this `'section': [101.86488640123036, 101.84]`, which appears to be points that got matched in intersections (but shouldn't happen since length tolerance is at 0.6). 

Example of a match with an  `empty` section with `gis.centreline` (5 in total)
![image](https://user-images.githubusercontent.com/46324452/54692301-2afd4980-4afb-11e9-8a48-6e8e5a0baa2f.png)

Example of a match with an `empty` section with `gis.centreline_both_way` (12 in total)
![image](https://user-images.githubusercontent.com/46324452/54950381-8a05f880-4f17-11e9-880a-93ad56f5adb5.png)

**Comment by chmnata** [comment]
We changed the value of section to (0, 0) which will be inserted as `empty` in the output table. The relationship between `reference_id` and `geo_id` only happened once in the output table (only one row with that `reference_id` and `geo_id`), thus we cannot delete the matched point. 

#8 This is an example of false positive match.

**Comment by chmnata** [comment]
We were trying to find out if those matches are correctly matched to the correct `reference_id`. So we looked into one example:
- `reference_id` = 2bd89366d5e997848927046442b8ccc1
- `geo_id` = 1750

The image shows the relationship of the above `reference_id` and `geo_id` is a result of incorrectly matched segments, where a small segment of the segment on top of the intersection (`geo_id`=1750) got matched as a "dot" below the intersection (which is a small line if you zoom in enough).

Image showing where the `geo_id` = 1750 is and the `reference_id` that got matched is located:

![image](https://user-images.githubusercontent.com/46324452/54951443-0b5e8a80-4f1a-11e9-85e5-d91abfc99708.png)

Image showing where the dot aka small segment is being matched:
![image](https://user-images.githubusercontent.com/46324452/54952114-92603280-4f1b-11e9-996f-cc21d0588429.png)

**Comment by chmnata** [comment]
This problem happened before in the here_evaluation where we were trying to match here links with bluetooth links using SharedStreets. We eliminated these incorrectly matched segment by finding the links that got matched with two analysis_id, rank the length of the intersection of analysis_id and corresponding links and eliminate the ones that has a length shorter than 7m.

**Comment by chmnata** [comment]
Went back and check the reference layers (`natalie.all_here_geom_routing`, `natalie.all_ssbt_geom_distinct`) created by SharedStreets during here_evaluation. There are no rows where lower bound has a higher number than upper bound.

**Comment by chmnata** [comment]
12 centreline streets that returned with a lower bound that is higher than upper bound in the `section` attribute: 
[Original Geojson](https://gist.githubusercontent.com/chmnata/9b97e28e7a1b7b03f74c9e5c95d847e0/raw/164e963a7f7f10ebec100c0c7b10143e9bfb84e0/issure_12_original_SS)
[Returned Geojson](https://gist.githubusercontent.com/chmnata/7febf7003cfb1f21e57962f6530fb701/raw/5841394ec66e9ce7ea0812aca4f4ae45550a27f0/issue_12_returned_SS)
![image](https://user-images.githubusercontent.com/46324452/55105925-0cbbbe80-50a4-11e9-85a4-983e6e53e886.png)

**Comment by emilyeros** [comment]
a) Can you tell me where those "dots" coming from? Are they an artifact of the HERE data and its offset?
b) Does snapping to intersections prevent this problem?

**Comment by chmnata** [comment]
a) Those small segments are caused by #14 where the offset-ed segments are so short that it resulted in those section values.
b) `snaptointersection=true` does seems to prevent #14  thus preventing this issue too
