### ISSUE TITLE
Create gis_shared_streets schema

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_shared_streets_conflator#7]

**Comment by radumas** [comment]
I created the `gis_shared_streets`  schema. You should create a table that will be the platonic ideal shared_streets table.

Every new table from that can be created with `CREATE gis_shared_streets.new_layer (LIKE gis_shared_streets.platonic_ideal_table)`

**Comment by chmnata** [comment]
Should it be a base table or a table that includes an additional variable column (e.g. original_id)? Cause they will all ended up having an additional column that is different for each dataset (e.g. centreline will need gid, bt will need analysis_id)

**Comment by radumas** [comment]
Ooh good point, `LIKE` just means copy over column definitions from that table, so there's room for naming the `id` column the appropriate name
https://devdocs.io/postgresql~9.6/sql-createtable

**Comment by chmnata** [comment]
ahh ok, if that's the case then I will make it as `::text` instead of `::integer`, considering some datasets have text identifiers (e.g. link_dir)

**Comment by radumas** [comment]
oh as in don't include the original id in this base table definition
